### ISSUE TITLE
Update project name where Neccessary - ProjectHunt

### ISSUE THREAD

**Issue by ThomasCarney315** [ImanKahlila/ProjectHunt#16]
Once the pull requests have been merged and the repo name has been updated, I will search through every repo file and update the name and URLs to reflect the new GitHub repo URL accurately. Then submit a pull request with the updates

Better to do it early!

**Comment by ThomasCarney315** [comment]
I added both of you so that we can change the name of the Repo. I know Kayla has access as the create, but Chelsey may also.
This screen snip should help 



![Image](https://user-images.githubusercontent.com/118192650/234802192-86340ca6-3c00-4e26-8707-6a0da8f5f7c5.png)

**Comment by ImanKahlila** [comment]
I renamed the repo to Project Hunt. I also merged one pull request. However, the last pull request has 3 conflicting files that need to be resolved. @Cheesely and @IntelliJinceTech can you guys please look into that. 

Thanks :)

**Comment by IntelliJinceTech** [comment]
I've resolved the original PR because it was still pointing to the old repo name and I think that may have caused some issues. I've since deleted it and opened a branch but looks like I don't have access still to create remote branches. See attached for the error. Hoping we can pair to get this resolved asap 

![image](https://user-images.githubusercontent.com/52391491/235559157-ca2341b1-6e9d-47c9-979e-3b968bbe46a8.png)

**Comment by ThomasCarney315** [comment]
> I've resolved the original PR by closing it with a comment because it was still pointing to the old repo name and I think that may have caused some issues. I've since opened a local branch but looks like I don't have access still to create remote branches. See attached for the error. Hoping we can pair to get this resolved asap
> 
> the command I used was just a simple git push origin `branch name`
> 
> ![image](https://user-images.githubusercontent.com/52391491/235559157-ca2341b1-6e9d-47c9-979e-3b968bbe46a8.png)

Hmm. If you fork it, make changes, and then submit a PR you should avoid any permission issues... I think.. I'm pretty sure
