### ISSUE TITLE
Complete ReadMe

### ISSUE THREAD

**Issue by ThomasCarney315** [ImanKahlila/ProjectHunt#18]
https://github.com/othneildrew/Best-README-Template

**Comment by IntelliJinceTech** [comment]
that template is fire! going to add the documentation tag so we can begin organizing discussions!

**Comment by andrewquach-dev** [comment]
Once the styling is done for the home page we can start working on the readme. Following the template you linked, we can add a screenshot or a live demo video in the About section.

**Comment by IreneLinWasHere** [comment]
This sounds like a great idea!
