### ISSUE TITLE
Vote between 2 Web Designs in Figma

### ISSUE THREAD

**Issue by ThomasCarney315** [ImanKahlila/ProjectHunt#21]
Please vote! 

Images attached are the homepages for Futuristic and Minimalist. More pages will be added when we decide on the final design.

I invited everyone to Figma as well, so check your emails. 

![Image](https://user-images.githubusercontent.com/110063712/235292790-c2575477-53a8-4965-b9ad-75efdc51e96d.png)

**Comment by ThomasCarney315** [comment]
Futuristic 
Wow, Great Job! on both

**Comment by Cheesely** [comment]
Minimalistic 👍

**Comment by andrewquach-dev** [comment]
They both look good. Minimalistic tho

**Comment by ImanKahlila** [comment]
I like them both! And thank you guys for the compliments! 💯 I'm going with Futuristic.

**Comment by Saviour-Dagadu** [comment]
Great work, this jet us to work now.! I will go for Futuristic.

**Comment by ImanKahlila** [comment]
Voting has been closed! Minimalistic won! We will keep in mind what @IntelliJinceTech suggested about changing to Futuristic depending on user feedback.

Thank you all for voting! We will be moving forward with creating the other pages to be Minimalist and code out the Frontend!
