### ISSUE TITLE
User should be able to create a project specifying, name, skills, skill level, GitHub URL and meeting times

### ISSUE THREAD

**Issue by Cheesely** [ImanKahlila/ProjectHunt#29]

**Comment by IntelliJinceTech** [comment]
From @andrewquach-dev 's diagram: https://lucid.app/lucidchart/abb93282-2a6a-416a-b3f4-e4df925a4522/edit?invitationId=inv_b6096bf0-b565-4e82-b2b6-5c6d678c41fe&page=4bxQfvkIw3VE#, we will probably need to update it for meeting times as well?

**Comment by andrewquach-dev** [comment]
> 

This is a good idea. I think the meeting time needs to be a full date and time so that it can be calculated for all user time zones.
