### ISSUE TITLE
compile list of time zones

### ISSUE THREAD

**Issue by ThomasCarney315** [ImanKahlila/ProjectHunt#33]
compile a simple list of time zones to be used for database/dropdown selection population

**Comment by ThomasCarney315** [comment]
I started researching time zones. There are a lot of options! I will make a simple list of 24 time zones UTC coordinated. I realized while thinking about it that keeping the options minimal will help a lot with matching / querying / etc.

**Comment by ImanKahlila** [comment]
Looks good!

**Comment by andrewquach-dev** [comment]
> also here, why not
> 
> ```
> (UTC -12) -12 GMT+12
> (UTC -11) SST Samoa Standard Time
> (UTC -10) HST Hawaii-Aleutian Standard Time
> (UTC -9) AKST Alaska Standard Time
> (UTC -8) PST Pacific Standard Time
> (UTC -7) MST Mountain Standard Time
> (UTC -6) CST Central Standard Time
> (UTC -5) EST Eastern Standard Time
> (UTC -4) AST Atlantic Standard Time
> (UTC -3) -03 GMT+3
> (UTC -2) -02 GMT+2
> (UTC -1) -01 GMT+1
> (UTC +0) GMT Greenwich Mean Time
> (UTC +1) CET Central European Time
> (UTC +2) CAT Central Africa Time
> (UTC +3) EAT East Africa Time
> (UTC +4) +04 GMT-4
> (UTC +5) PKT Pakistan Standard Time
> (UTC +6) +06 GMT-6
> (UTC +7) WIB Western Indonesia Time
> (UTC +8) HKT Hong Kong Time
> (UTC +9) JST Japan Standard Time
> (UTC +10) AEST Australian Eastern Standard Time
> (UTC +11) +11 GMT-11
> (UTC +12) NZST New Zealand Standard Time 
> (UTC +13) +13 GMT-13
> (UTC +14) +14 GMT-14
> ```

Hey Thomas I was thinking of having a library handle all of this work. There's a library called moment-timezone that can make pre-defined list of time zones and utilities to work with them

**Comment by ThomasCarney315** [comment]
Sure. Whatever you think is going to work better. I think the priority for the timezone list is to be minimal to eliminate the excessive variability in timezones resulting in more matches..(it would be a shame for people to miss opportunities by simply choosing a different option for the same time)

If it can meet that requirement and has tools, I say perfect!

I was thinking how it would be ideal to be able to match timezones within say {3} hours in either direction of your current tz... how to do this.. idk. It would be awesome if it has tools for that

**Comment by andrewquach-dev** [comment]
I've never used it before but from a quick glance at the doc, it seems that it can manipulate, compare and format all things dates, times, and timezones.
