### ISSUE TITLE
Create and implement CSS styles for login and signup page

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#41]
**Checklist:**
- [x] Create layout on figma or interface design tool of choice (https://www.figma.com/file/KkvsssHp93VMicvdxQR8au/Untitled?type=design&node-id=0-1&t=opF5UaaTqxMnVlcN-0)
- [x] Create CSS styles based on layout

**Comment by Kanchan253** [comment]
Hi @andrewquach-dev , I would like to work on this. Kindly assign this to me. And also can I know what you have in mind for the signup and login page design

**Comment by andrewquach-dev** [comment]
> Hi @andrewquach-dev , I would like to work on this. Kindly assign this to me. And also can I know what you have in mind for the signup and login page design

I think you should design something similar to what @ImanKahlila designed. Once you've designed it, you can get feedback, and we can collaborate here. Finally, you can convert the design to CSS.

**Comment by ThomasCarney315** [comment]
@ImanKahlila is the owner of that Figma file. They can approve your request.

**Comment by Kanchan253** [comment]
Hi @ImanKahlila I have sent a request for viewing the figma linked above , can you please grant me access so I can start on this.

**Comment by ImanKahlila** [comment]
@Kanchan253 I approved your viewing on Figma. Also you can check out everything as far as frontend design for this project in the Discussions.

**Comment by Cheesely** [comment]
Hey @Kanchan253 i might also be a good idea to ensure you collaborate with @IntelliJinceTech considering he is working on the [sign in with discord and/or github ticket](https://github.com/ImanKahlila/ProjectHunt/issues/30). I'm not 💯 sure that collaboration is necessary but it seems like there might be enough crossover to at least check in with each other considering both of these issues are being dealt with on totally different branches.

**Comment by IreneLinWasHere** [comment]
Question: for the alternative sign in methods (via GitHub and Discord), is it better to use pictures for the logos or icons from Font Awesome?

**Comment by ImanKahlila** [comment]
I would prefer the logos/pictures, but it’ll probably be a copyright issue.
So I’d say use icons from Font Awesome. I’m sure it’s free icons for GitHub
and Discord though.

**Comment by ThomasCarney315** [comment]
> Question: for the alternative sign in methods (via GitHub and Discord), is it better to use pictures for the logos or icons from Font Awesome?

I think its preference and style more than anything. I like Working with icons and .svg images; they are simple and clean looking

**Comment by IreneLinWasHere** [comment]
I'm done styling the page, there is a weird issue with an extra login and sign up link. I'm not sure what is causing this. Could someone please help?

<img width="816" alt="extra login and sign up" src="https://github.com/ImanKahlila/ProjectHunt/assets/111097252/efafbef9-5000-4601-8d3e-0c1fee92704a">

**Comment by andrewquach-dev** [comment]
> 

I think the issue is that the comments are being misinterpreted as EJS so deleting the comment stuff should fix it.
![image](https://github.com/ImanKahlila/ProjectHunt/assets/8891067/a466dfe8-c504-4089-bc72-4367acaced4d)

Also, why is there a second branch called reset?

**Comment by IreneLinWasHere** [comment]
Thanks, that did the trick!

Re: 2nd branch, I couldn't resolve the issues I was having with Git on Friday, so I decided to abandon ship, make a new clone, and copy my files over. The 2nd branch was just in case I messed that up somehow.
