### ISSUE TITLE
Create and implement CSS styles for home page

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#43]
**Checklist:**
- [ ] Create layout on figma or interface design tool of choice (https://www.figma.com/file/KkvsssHp93VMicvdxQR8au/Untitled?type=design&node-id=0-1&t=opF5UaaTqxMnVlcN-0)
- [ ] Create CSS styles based on layout

**Comment by Cheesely** [comment]
https://www.figma.com/proto/KkvsssHp93VMicvdxQR8au/Project-Hunt?type=design&node-id=0-1&scaling=scale-down&starting-point-node-id=219%3A2
