### ISSUE TITLE
Update navigation items on login

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#46]
**Description:**
When users log in to the website, it would greatly improve the user experience if the navigation items dynamically reflect their authentication status. Currently, when users are logged out, the navigation menu displays "Login" and "Signup" options. However, after logging in, these options should be updated to "Profile" and "Logout" to provide consistency and enable easy access to relevant actions.

![Image](https://github.com/ImanKahlila/ProjectHunt/assets/8891067/35f06e92-e5ea-4f36-b692-9c7fdbc7892b)

**Checklist:**
- [ ] Research an EJS way of conditionally hiding an HTML element depending on if a user is logged in or not
- [ ] Alter EJS file with above code

**Comment by kaleemullah786** [comment]
hey can i work on this
