### ISSUE TITLE
Create and implement CSS styles for browse projects page

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#47]
**Checklist:**
- [ ] Create layout on figma or interface design tool of choice (https://www.figma.com/file/KkvsssHp93VMicvdxQR8au/Untitled?type=design&node-id=0-1&t=opF5UaaTqxMnVlcN-0)
- [ ] Create CSS styles based on layout

**Comment by haiderali88g** [comment]
Hey @andrewquach-dev, I would love to do that for you. Assign this to me.
I have also requested access file for figma design.

**Comment by Cheesely** [comment]
@haiderali88g how is this issue going? Do you need any help with it?

**Comment by ImanKahlila** [comment]
@Cheesely That's someone that was looking for open-source projects but we decided that it isn't open source. So someone else needs to do this page.

**Comment by Cheesely** [comment]
Ah ok! I’ll assign it to myself then!

**Comment by ImanKahlila** [comment]
Great! I went ahead and did it for you. I'm doing the homepage.
