### ISSUE TITLE
Implement organization selection in project creation page

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#52]
Allow users to select the organization and update the router and controller to support this feature. the following tasks need to be completed:

1. Front-End Changes:

       - Modify the project creation page to include a field for users to select/input organization.

       - Implement autocompletion functionality to suggest existing organizations as the user types.

2. Back-End Changes:

       - Update the router
       - Modify controller

**Comment by ThomasCarney315** [comment]
Created pull PR-#58 https://github.com/ImanKahlila/ProjectHunt/pull/58#issuecomment-1596285385
