### ISSUE TITLE
Improve README instructions for a more welcoming onboarding experience

### ISSUE THREAD

**Issue by andrewquach-dev** [ImanKahlila/ProjectHunt#57]

**Comment by ThomasCarney315** [comment]
@IreneLinWasHere 
Maybe you can include a tip to remember to click the "update user" button when you need to change the password for DB connection string. 
This really messed me up 😅


![Image](https://github.com/ImanKahlila/ProjectHunt/assets/118192650/911f66a4-da69-4d5e-b62f-3d4a00dd331a)


![Image](https://github.com/ImanKahlila/ProjectHunt/assets/118192650/c113a5e9-1810-46f8-9203-7fd021f55f1b)

**Comment by IreneLinWasHere** [comment]
Sure, no problem!

I added the following to step 6:

"Tip: should you need to update a database user, please remember to click the green button that says "Update User" to save your changes."

Do you think that sounds clear?

**Comment by ThomasCarney315** [comment]
Perfect!
